name: CMake Release

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - test/**
      - .github/workflows/cmake.yml
  pull_request:
    branches:
      - '**'
    paths:
      - src/**
      - test/**
      - .github/workflows/cmake.yml
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_dlib_ext: .so 
            artifact_staticlib_ext: .a
          - os: windows-latest
            artifact_exec_ext: .exe
            artifact_dlib_ext: .dll
            artifact_staticlib_ext: .lib
            # Note: I wanted to use env.BUILD_TYPE, but it isn't taking
            #artifact_out_dir: ${{ BUILD_TYPE }}/
            artifact_out_dir: Release/
            artifact_os_name: Windows
            artifact_arch: x86_64
          - os: macos-latest
            artifact_dlib_ext: .dylib
            artifact_staticlib_ext: .a
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install libgl1-mesa-dev mesa-utils libgl1-mesa-glx libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
      if: matrix.os == 'ubuntu-latest'
    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Cache C++ dependencies in Packages Directory
      uses: actions/cache@v3
      with:
        path: |
          packages
        key: ${{ runner.OS }}-c++-packages-cache-Release-${{ hashFiles('depsCache.json') }}
        restore-keys: |
          ${{ runner.OS }}-c++-packages-cache-Release-

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS="-coverage"

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE
    - name: Set variables (Mac\Linux)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
      run: |
        APP=$(cat $GITHUB_WORKSPACE/src/version/AppName.txt)
        VER=$(cat $GITHUB_WORKSPACE/src/version/Version.txt)
        echo "VERSION=$VER" >> $GITHUB_ENV
        echo "APPNAME=$APP" >> $GITHUB_ENV
    - name: Set variables (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        $APP = type .\src\version\AppName.txt
        $VER = type .\src\version\Version.txt
        echo "VERSION=$VER" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        echo "APPNAME=$APP" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
    - name: Test Unix-like
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ./test/${{ env.APPNAME }}_TEST

    - name: Test Windows
      if: matrix.os == 'windows-latest'
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ./test/Release/${{ env.APPNAME }}_TEST.exe
    
    - name: Linux Code Coverage
      if: matrix.os == 'ubuntu-latest'
      working-directory: ${{github.workspace}}
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ./scripts/runGcov.sh
    - name: Prepare Binaries for upload (Mac\Linux)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
      shell: bash
      run:  |
        mkdir ${{github.workspace}}/artifacts
        cp build/src/lib${{ env.APPNAME }}${{ matrix.artifact_staticlib_ext }} ${{github.workspace}}/artifacts
        cp build/src/main/${{ env.APPNAME }}_exe ${{github.workspace}}/artifacts
        cp -r build/src/main/shaders ${{github.workspace}}/artifacts
        pushd ${{github.workspace}}
        zip -r ${{ env.APPNAME }}-$(uname -s)-$(uname -m).zip artifacts
        popd
    - name: Prepare Binaries for upload (windows)
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        [system.io.directory]::CreateDirectory("${{github.workspace}}/artifacts")
        Copy-Item "build/src/${{ matrix.artifact_out_dir}}${{ env.APPNAME }}${{ matrix.artifact_staticlib_ext }}" -Destination "${{github.workspace}}/artifacts"
        Copy-Item "build/src/main/${{ matrix.artifact_out_dir }}${{ env.APPNAME }}_exe${{ matrix.artifact_exec_ext }}" -Destination "${{github.workspace}}/artifacts"
        Compress-Archive -Path ${{github.workspace}}/artifacts/* -DestinationPath ${{ env.APPNAME }}-${{matrix.artifact_os_name}}-${{matrix.artifact_arch}}.zip
    - name: 'Upload Pull Request Artifact'
      uses: actions/upload-artifact@v3
      if: startsWith(github.ref, 'refs/pull/')
      with:
        name: ${{ env.APPNAME }} Pull Request Artifacts
        path: ${{ env.APPNAME }}-*.zip
        retention-days: 5
    - name: Upload binaries to Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/heads/master')
      with:
        tag_name: ${{ env.APPNAME }}-${{ env.VERSION }}
        files: |
          ${{ env.APPNAME }}-*.zip
